###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "email": "pcjpcj2@gmail.com",
  "password": "password"
}

###
GET http://localhost:3000/articles HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1YjAxN2Q5LWVmMzAtNDNmZS05M2QyLWQ1ZTBlZmMwMjljNiIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NDAzODYwNzF9.VOrs7luvV4EB13-M6W2caC_r2uVmVQip-73vJqRLOsk
Content-Type: application/json
Accept: application/json

###
GET http://localhost:3000/articles/9e112f5c-863f-497e-a20f-e42da7aec95b HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAxMjg1MDV9.E4-l3YcLeSq3DWIbJGxSAxMu1STnw-T8WhXE2Pi72j8
Content-Type: application/json
Accept: application/json


###
POST http://localhost:3000/api/articles HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMzkzYmYxLTE4N2YtNDRmNy05Y2JlLTdkY2Q3Yzg3YzU1MCIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6IkFkbWluaXN0cmF0b3IiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NDA2NDQwNzd9.KBsILlZ07bI4jdc9LadJieXmgdcB5VNgByvuAwc-sgo
Content-Type: application/json
Accept: application/json

{
  "title": "Microsoft",
  "body": "testing",
  "topicId": "9517936f-c4f6-4f8b-b4f3-6f11ce76f4b4"
}

###
POST http://localhost:3000/topics HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAxMjg1MDV9.E4-l3YcLeSq3DWIbJGxSAxMu1STnw-T8WhXE2Pi72j8
Content-Type: application/json
Accept: application/json

{
  "name": "Accounts",
  "description": "save for accounts"
}

###
PATCH http://localhost:3000/topics/c014fd2d-65ce-414c-b419-043f2337237b HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAxMjg1MDV9.E4-l3YcLeSq3DWIbJGxSAxMu1STnw-T8WhXE2Pi72j8
Content-Type: application/json
Accept: application/json

{
  "name": "Hello World",
  "description": "hi"
}

###
GET http://localhost:3000/topics/c014fd2d-65ce-414c-b419-043f2337237b HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAxMjg1MDV9.E4-l3YcLeSq3DWIbJGxSAxMu1STnw-T8WhXE2Pi72j8
Content-Type: application/json
Accept: application/json


###
GET http://localhost:3000/topics HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAxMjg1MDV9.E4-l3YcLeSq3DWIbJGxSAxMu1STnw-T8WhXE2Pi72j8
###
GET http://localhost:3000/topics/c014fd2d-65ce-414c-b419-043f2337237b/articles HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAxMjg1MDV9.E4-l3YcLeSq3DWIbJGxSAxMu1STnw-T8WhXE2Pi72j8


# ADMIN ONLY
###
DELETE http://localhost:3000/articles HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAxMjg1MDV9.E4-l3YcLeSq3DWIbJGxSAxMu1STnw-T8WhXE2Pi72j8

###
DELETE http://localhost:3000/topics HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAxMjg1MDV9.E4-l3YcLeSq3DWIbJGxSAxMu1STnw-T8WhXE2Pi72j8

# Update Article - TODO: Check create archive
###
PATCH http://localhost:3000/articles/5f6cdd88-9f29-423e-aeb5-68460fea3bb7 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAyMTE0MDd9.bvsSfp6CHKnDewvsTUv6iJBueOnLiQo4TI3Bwm3OmVw

{
  "title": "[Patch] Title Really Changed3",
  "body": "[Patch] Body Really Changed3",
  "whatChanged": "이 내용은 아티클에 222함"
}


###
GET http://localhost:3000/articles/4f64d0d7-c85d-446f-aa68-af7744b7a178/history HTTP/1.1

###
GET http://localhost:3000 HTTP/1.1

###
GET http://localhost:3000/profile HTTP/1.1


###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1YjAxN2Q5LWVmMzAtNDNmZS05M2QyLWQ1ZTBlZmMwMjljNiIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NDAyMTk2MDF9.Gf8_MvETPT7Btmcbm5_rR3SA9MTBGeaDlUoeSKW0sPw

{
  "email": "pcjpcj4@gmail.com",
  "username": "changjoo-park4",
  "password": "password"
}

###
GET http://localhost:3000/me HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1YjAxN2Q5LWVmMzAtNDNmZS05M2QyLWQ1ZTBlZmMwMjljNiIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NDAyOTc0OTl9.9bCk_p4va8j0i_XkVUrcDT49r370Bh97g1iGRGs9txo


###
GET http://localhost:3000/setup/check HTTP/1.1
Content-Type: application/json
Accept: application/json


###
POST http://localhost:3000/setup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "user": {
    "email": "pcjpcj2@gmail.com",
    "password": "password",
    "username": "changjoo-park"
  },
  "service": {
    "name": "BetterWiki",
    "description": "This is My wikiwiki"
  }
}


###
GET http://localhost:3000/service HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAxMjg1MDV9.E4-l3YcLeSq3DWIbJGxSAxMu1STnw-T8WhXE2Pi72j8

###
GET http://localhost:3000/users HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1YjAxN2Q5LWVmMzAtNDNmZS05M2QyLWQ1ZTBlZmMwMjljNiIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NDAyOTYzMDh9.r21r9jvKStYu0feKT0UPppXrPX1WPLsOKqvBManN1hc
Content-Type: application/json
Accept: application/json

###
GET http://localhost:3000/users/2989e48b-3c69-4a6b-8783-59c8d5b1c39c HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAxMjg1MDV9.E4-l3YcLeSq3DWIbJGxSAxMu1STnw-T8WhXE2Pi72j8
Content-Type: application/json
Accept: application/json


###
PATCH http://localhost:3000/topics/c014fd2d-65ce-414c-b419-043f2337237b/articles/45d8ebad-7390-4e7a-943a-f901390d23f7/connect HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAxMjg1MDV9.E4-l3YcLeSq3DWIbJGxSAxMu1STnw-T8WhXE2Pi72j8
Content-Type: application/json
Accept: application/json

###
DELETE http://localhost:3000/topics/c014fd2d-65ce-414c-b419-043f2337237b/articles/45d8ebad-7390-4e7a-943a-f901390d23f7/disconnect HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODllNDhiLTNjNjktNGE2Yi04NzgzLTU5YzhkNWIxYzM5YyIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDE4LTEwLTIxVDExOjU4OjI2LjAwMFoiLCJpYXQiOjE1NDAxMjg1MDV9.E4-l3YcLeSq3DWIbJGxSAxMu1STnw-T8WhXE2Pi72j8
Content-Type: application/json
Accept: application/json


###
PATCH http://localhost:3000/users/b0a306cc-90dd-471f-8d56-a1f7d9c6e1de HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1YjAxN2Q5LWVmMzAtNDNmZS05M2QyLWQ1ZTBlZmMwMjljNiIsImVtYWlsIjoicGNqcGNqMkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoYW5nam9vLXBhcmsiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NDAyOTYzMDh9.r21r9jvKStYu0feKT0UPppXrPX1WPLsOKqvBManN1hc
Content-Type: application/json
Accept: application/json

{
  "about": "Hello World",
  "avatar": "http://www.gravatar.com/avatar/73543542128f5a067ffc34305eefe48a",
  "role": "asdf"
}
