###
GET http://localhost:3000/articles HTTP/1.1

###
GET http://localhost:3000/articles/4f64d0d7-c85d-446f-aa68-af7744b7a178 HTTP/1.1


###
POST http://localhost:3000/articles HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "title": "Second related article",
  "body": "Lorem Ipsum aasdfasdfasdfa",
  "topicId": "9687df87-ef5f-47c0-938e-922b711a0038"
}

###
POST http://localhost:3000/topics HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "FirstTopic",
  "description": "This is first Topic"
}

###
GET http://localhost:3000/topics HTTP/1.1

###
GET http://localhost:3000/topics/9687df87-ef5f-47c0-938e-922b711a0038/articles HTTP/1.1


# ADMIN ONLY
###
DELETE http://localhost:3000/articles HTTP/1.1


# Update Article - TODO: Check create archive
###
PATCH http://localhost:3000/articles/4f64d0d7-c85d-446f-aa68-af7744b7a178 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "title": "[Patch] Title Really Changed3",
  "body": "[Patch] Body Really Changed3",
  "whatChanged": "이 내용은 아티클에 222함"
}

###
GET http://localhost:3000/articles/4f64d0d7-c85d-446f-aa68-af7744b7a178/history HTTP/1.1

###
GET http://localhost:3000 HTTP/1.1

###
GET http://localhost:3000/profile HTTP/1.1

###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "email": "pcjpcj2@gmail.com",
  "password": "mypassowrd"
}

###
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "email": "pcjpcj2@gmail.com",
  "password": "mypassowrd"
}
